/**
 * Do not edit this file directly.
 * Instead, edit the appropriate spreadsheet
 * https://docs.google.com/spreadsheets/d/102zLqEWj4xlqqNgVUFCiMLqdcvaLY6GntS1xmlHdAE8/edit#gid=0
 * and recompile in order to change these fields
 */
import { TranslationFile } from "../Types";
declare const es_ES: TranslationFile;
export { es_ES };
